

from rapidfuzz import fuzz, process
import sqlite3
conn = sqlite3.connect('doseiq.db')
cursor = conn.cursor()

cursor.execute('''
	CREATE TABLE IF NOT EXISTS medicine_disease (
		medicine_name TEXT NOT NULL,
		disease TEXT NOT NULL
	)
''')
conn.commit()

medicines = [
	("Paracetamol", "common"),
	("Ibuprofen", "common"),
	("Cetirizine", "common"),
	("Loratadine", "common"),
	("Levocetirizine", "common"),
	("Ranitidine", "common"),
	("Famotidine", "common"),
	("Domperidone", "common"),
	("Ondansetron", "common"),
	("Oral Rehydration Salts (ORS)", "common"),
	("Loperamide", "common"),
	("Dextromethorphan", "common"),
	("Guaifenesin", "common"),
	("Ambroxol", "common"),
	("Povidone-Iodine", "common"),
	("Hydrogen Peroxide", "common"),
	("Neomycin", "common"),
	("Bacitracin", "common"),
	("Clotrimazole", "common"),
	("Miconazole", "common"),
	("Fluconazole", "common"),
	("Salbutamol", "common"),
	("Montelukast", "common"),
	("Vitamin C", "common"),
	("Vitamin D3", "common"),
	("Calcium Carbonate", "common"),
	("Ferrous Sulfate", "common"),
	("Folic Acid", "common"),
	("Zinc Sulfate", "common"),
	("Magnesium Hydroxide", "common"),
	("Sodium Bicarbonate", "common"),
	("Naproxen", "common"),
	("Diclofenac", "common"),
	("Chlorpheniramine", "common"),
	("Prednisolone", "common"),
	("Hydrocortisone", "common"),
	("Budesonide", "common"),
	("Beclomethasone", "common"),
	("Theophylline", "common"),
	("Thiamine", "common"),
	("Riboflavin", "common"),
	("Niacin", "common"),
	("Multivitamins", "common"),
	("Metronidazole", "common"),
	("Ciprofloxacin", "common"),
	("Doxycycline", "common"),
	("Ofloxacin", "common"),
	("Levofloxacin", "common"),
	("Amoxicillin", "common"),
	("Azithromycin", "common"),
	("Clarithromycin", "common"),
	("Aspirin", "heart"),
	("Clopidogrel", "heart"),
	("Prasugrel", "heart"),
	("Ticagrelor", "heart"),
	("Warfarin", "heart"),
	("Apixaban", "heart"),
	("Rivaroxaban", "heart"),
	("Dabigatran", "heart"),
	("Heparin", "heart"),
	("Enoxaparin", "heart"),
	("Atenolol", "heart"),
	("Metoprolol", "heart"),
	("Bisoprolol", "heart"),
	("Carvedilol", "heart"),
	("Propranolol", "heart"),
	("Amlodipine", "heart"),
	("Nifedipine", "heart"),
	("Felodipine", "heart"),
	("Verapamil", "heart"),
	("Diltiazem", "heart"),
	("Losartan", "heart"),
	("Valsartan", "heart"),
	("Telmisartan", "heart"),
	("Olmesartan", "heart"),
	("Candesartan", "heart"),
	("Ramipril", "heart"),
	("Enalapril", "heart"),
	("Lisinopril", "heart"),
	("Perindopril", "heart"),
	("Captopril", "heart"),
    ("Hydrochlorothiazide", "heart"),
    ("Chlorthalidone", "heart"),
	("Indapamide", "heart"),
	("Furosemide", "heart"),
	("Spironolactone", "heart"),
	("Eplerenone", "heart"),
	("Isosorbide Mononitrate", "heart"),
	("Isosorbide Dinitrate", "heart"),
    ("Nitroglycerin", "heart"),
    ("Ranolazine", "heart"),
    ("Ivabradine", "heart"),
    ("Digoxin", "heart"),
    ("Amiodarone", "heart"),
	("Sotalol", "heart"),
	("Flecainide", "heart"),
	("Propafenone", "heart"),
	("Atorvastatin", "heart"),
	("Rosuvastatin", "heart"),
	("Simvastatin", "heart"),
	("Ezetimibe", "heart"),
	("Amlodipine", "bloodpressure"),
	("Telmisartan", "bloodpressure"),
	("Losartan", "bloodpressure"),
	("Enalapril", "bloodpressure"),
	("Lisinopril", "bloodpressure"),
	("Ramipril", "bloodpressure"),
	("Olmesartan", "bloodpressure"),
	("Metoprolol", "bloodpressure"),
	("Atenolol", "bloodpressure"),
	("Bisoprolol", "bloodpressure"),
	("Carvedilol", "bloodpressure"),
	("Furosemide", "bloodpressure"),
	("Hydrochlorothiazide", "bloodpressure"),
	("Chlorthalidone", "bloodpressure"),
	("Clonidine", "bloodpressure"),
	("Methyldopa", "bloodpressure"),
	("Captopril", "bloodpressure"),
	("Nebivolol", "bloodpressure"),
	("Labetalol", "bloodpressure"),
	("Aliskiren", "bloodpressure"),
	("Diltiazem", "bloodpressure"),
	("Verapamil", "bloodpressure"),
	("Felodipine", "bloodpressure"),
	("Nifedipine", "bloodpressure"),
	("Hydralazine", "bloodpressure"),
	("Bendroflumethiazide", "bloodpressure"),
	("Prazosin", "bloodpressure"),
	("Propranolol", "bloodpressure"),
	("Spironolactone", "bloodpressure"),
	("Eplerenone", "bloodpressure"),
	("Minoxidil", "bloodpressure"),
	("Terazosin", "bloodpressure"),
	("Guazatin", "bloodpressure"),
	("Moxonidine", "bloodpressure"),
	("Doxazosin", "bloodpressure"),
	("Aliskiren", "bloodpressure"),
	("Torsemide", "bloodpressure"),
	("Indapamide", "bloodpressure"),
	("Amiloride", "bloodpressure"),
	("Clonidine", "bloodpressure"),
	("Nitroprusside", "bloodpressure"),
	("Nadolol", "bloodpressure"),
	("Acebutolol", "bloodpressure"),
	("Celiprolol", "bloodpressure"),
	("Esmolol", "bloodpressure"),
	("Methyldopa", "bloodpressure"),
	("Oxprenolol", "bloodpressure"),
	("Trimethaphan", "bloodpressure"),
	("Salbutamol", "Breathing"),
	("Levosalbutamol", "Breathing"),
	("Theophylline", "Breathing"),
	("Montelukast", "Breathing"),
	("Zafirlukast", "Breathing"),
	("Epinephrine", "Breathing"),
	("Formoterol", "Breathing"),
	("Salmeterol", "Breathing"),
	("Beclomethasone", "Breathing"),
	("Budesonide", "Breathing"),
	("Fluticasone", "Breathing"),
	("Triamcinolone", "Breathing"),
	("Methylprednisolone", "Breathing"),
	("Prednisolone", "Breathing"),
	("Dexamethasone", "Breathing"),
	("Hydrocortisone", "Breathing"),
	("Cromolyn sodium", "Breathing"),
	("Ketotifen", "Breathing"),
	("Guaifenesin", "Breathing"),
	("N-Acetylcysteine", "Breathing"),
	("Phenylephrine", "Breathing"),
	("Oxymetazoline", "Breathing"),
	("Tiotropium", "Breathing"),
	("Ipratropium", "Breathing"),
	("Glycopyrrolate", "Breathing"),
	("Acebrophylline", "Breathing"),
	("Terbutaline", "Breathing"),
	("Mepolizumab", "Breathing"),
	("Omalizumab", "Breathing"),
	("Benralizumab", "Breathing"),
	("Oxygen", "Breathing"),
	("Leukotriene receptor antagonist", "Breathing"),
	("Oral corticosteroid", "Breathing"),
	("Short-acting beta agonist", "Breathing"),
	("Long-acting beta agonist", "Breathing"),
	("Inhaled corticosteroid", "Breathing"),
	("Bronchodilator", "Breathing"),
	("Mast cell stabilizer", "Breathing"),
	("Immunomodulator", "Breathing"),
	("Nebulizer solution", "Breathing"),
	("Metered-dose inhaler", "Breathing"),
	("Dry powder inhaler", "Breathing"),
	("Spacer device", "Breathing"),
	("Spacer", "Breathing"),
	("Rescue inhaler", "Breathing"),
	("Controller medication", "Breathing"),
	("Oral leukotriene inhibitor", "Breathing"),
	("Biologic therapy", "Breathing"),
	("Beta-2 agonist", "Breathing"),
	("Fluoxetine", "mentalhealth"),
	("Sertraline", "mentalhealth"),
	("Paroxetine", "mentalhealth"),
	("Escitalopram", "mentalhealth"),
	("Citalopram", "mentalhealth"),
	("Venlafaxine", "mentalhealth"),
	("Duloxetine", "mentalhealth"),
	("Desvenlafaxine", "mentalhealth"),
	("Amitriptyline", "mentalhealth"),
	("Nortriptyline", "mentalhealth"),
	("Imipramine", "mentalhealth"),
	("Clomipramine", "mentalhealth"),
	("Bupropion", "mentalhealth"),
	("Mirtazapine", "mentalhealth"),
	("Trazodone", "mentalhealth"),
	("Vortioxetine", "mentalhealth"),
	("Lithium", "mentalhealth"),
	("Valproic acid", "mentalhealth"),
	("Carbamazepine", "mentalhealth"),
	("Lamotrigine", "mentalhealth"),
	("Olanzapine", "mentalhealth"),
	("Risperidone", "mentalhealth"),
	("Quetiapine", "mentalhealth"),
	("Aripiprazole", "mentalhealth"),
	("Ziprasidone", "mentalhealth"),
	("Haloperidol", "mentalhealth"),
	("Chlorpromazine", "mentalhealth"),
	("Fluphenazine", "mentalhealth"),
	("Clozapine", "mentalhealth"),
	("Asenapine", "mentalhealth"),
	("Paliperidone", "mentalhealth"),
	("Buspirone", "mentalhealth"),
	("Diazepam", "mentalhealth"),
	("Lorazepam", "mentalhealth"),
	("Clonazepam", "mentalhealth"),
	("Alprazolam", "mentalhealth"),
	("Oxazepam", "mentalhealth"),
	("Temazepam", "mentalhealth"),
	("Zolpidem", "mentalhealth"),
	("Eszopiclone", "mentalhealth"),
	("Suvorexant", "mentalhealth"),
	("Propranolol", "mentalhealth"),
	("Gabapentin", "mentalhealth"),
	("Pregabalin", "mentalhealth"),
	("Hydroxyzine", "mentalhealth"),
	("Prazosin", "mentalhealth"),
	("Thiothixene", "mentalhealth"),
	("Perphenazine", "mentalhealth"),
	("Trifluoperazine", "mentalhealth"),
	("Lurasidone", "mentalhealth"),
	("Timolol", "eye"),
	("Betaxolol", "eye"),
	("Levobunolol", "eye"),
	("Carteolol", "eye"),
	("Bimatoprost", "eye"),
	("Latanoprost", "eye"),
	("Travoprost", "eye"),
	("Tafluprost", "eye"),
	("Brimonidine", "eye"),
	("Apraclonidine", "eye"),
	("Dorzolamide", "eye"),
	("Brinzolamide", "eye"),
	("Acetazolamide", "eye"),
	("Pilocarpine", "eye"),
	("Carbachol", "eye"),
	("Atropine", "eye"),
	("Homatropine", "eye"),
	("Cyclopentolate", "eye"),
	("Tropicamide", "eye"),
	("Phenylephrine", "eye"),
	("Dexamethasone", "eye"),
	("Prednisolone acetate", "eye"),
	("Loteprednol", "eye"),
	("Fluorometholone", "eye"),
	("Rimexolone", "eye"),
	("Ketorolac", "eye"),
	("Diclofenac", "eye"),
	("Nepafenac", "eye"),
	("Bromfenac", "eye"),
	("Chloramphenicol", "eye"),
	("Tobramycin", "eye"),
	("Gentamicin", "eye"),
	("Moxifloxacin", "eye"),
	("Gatifloxacin", "eye"),
	("Levofloxacin", "eye"),
	("Ofloxacin", "eye"),
	("Ciprofloxacin", "eye"),
	("Acyclovir", "eye"),
	("Ganciclovir", "eye"),
	("Natamycin", "eye"),
	("Amphotericin B", "eye"),
	("Voriconazole", "eye"),
	("Hypromellose", "eye"),
	("Carboxymethylcellulose", "eye"),
	("Polyethylene glycol", "eye"),
	("Povidone", "eye"),
	("Sodium hyaluronate", "eye"),
	("Cyclosporine", "eye"),
	("Lifitegrast", "eye"),
	("Oxybuprocaine", "eye"),
	("Xylometazoline", "ent"),
	("Oxymetazoline", "ent"),
	("Naphazoline", "ent"),
	("Phenylephrine", "ent"),
	("Pseudoephedrine", "ent"),
	("Cetirizine", "ent"),
	("Levocetirizine", "ent"),
	("Loratadine", "ent"),
	("Fexofenadine", "ent"),
	("Chlorpheniramine", "ent"),
	("Diphenhydramine", "ent"),
	("Azelastine", "ent"),
	("Olopatadine", "ent"),
	("Fluticasone", "ent"),
	("Mometasone", "ent"),
	("Budesonide", "ent"),
	("Beclomethasone", "ent"),
	("Triamcinolone", "ent"),
	("Saline nasal spray", "ent"),
	("Sodium chloride", "ent"),
	("Betahistine", "ent"),
	("Meclizine", "ent"),
	("Cinnarizine", "ent"),
	("Dimenhydrinate", "ent"),
	("Acetylcysteine", "ent"),
	("Carbocisteine", "ent"),
	("Ambroxol", "ent"),
	("Bromhexine", "ent"),
	("Guaifenesin", "ent"),
	("Amoxicillin", "ent"),
	("Ampicillin", "ent"),
	("Cefuroxime", "ent"),
	("Cefixime", "ent"),
	("Ceftriaxone", "ent"),
	("Ciprofloxacin", "ent"),
	("Ofloxacin", "ent"),
	("Moxifloxacin", "ent"),
	("Gentamicin", "ent"),
	("Tobramycin", "ent"),
	("Neomycin", "ent"),
	("Clotrimazole", "ent"),
	("Miconazole", "ent"),
	("Ketoconazole", "ent"),
	("Amphotericin B", "ent"),
	("Acyclovir", "ent"),
	("Hydrogen peroxide", "ent"),
	("Acetic acid", "ent"),
	("Boric acid", "ent"),
	("Lignocaine", "ent"),
	("Ursodeoxycholic acid", "liver"),
	("Silymarin", "liver"),
	("Essential phospholipids", "liver"),
	("Glutathione", "liver"),
	("L-ornithine L-aspartate", "liver"),
	("Adefovir", "liver"),
	("entecavir", "liver"),
	("Tenofovir disoproxil fumarate", "liver"),
	("Tenofovir alafenamide", "liver"),
	("Lamivudine", "liver"),
	("Telbivudine", "liver"),
	("Peginterferon alfa-2a", "liver"),
	("Peginterferon alfa-2b", "liver"),
	("Ribavirin", "liver"),
	("Sofosbuvir", "liver"),
	("Ledipasvir", "liver"),
	("Velpatasvir", "liver"),
	("Glecaprevir", "liver"),
	("Pibrentasvir", "liver"),
	("Daclatasvir", "liver"),
	("Elbasvir", "liver"),
	("Grazoprevir", "liver"),
	("Boceprevir", "liver"),
	("Telaprevir", "liver"),
	("Simeprevir", "liver"),
	("Ombitasvir", "liver"),
	("Paritaprevir", "liver"),
	("Dasabuvir", "liver"),
	("Cholic acid", "liver"),
	("Chenodeoxycholic acid", "liver"),
	("Vitamin E", "liver"),
	("Vitamin K1 (Phytonadione)", "liver"),
	("Thiamine (Vitamin B1)", "liver"),
	("Folic acid", "liver"),
	("Rifaximin", "liver"),
	("Lactulose", "liver"),
	("Neomycin", "liver"),
	("Metronidazole", "liver"),
	("N-acetylcysteine", "liver"),
	("S-adenosylmethionine", "liver"),
	("Obeticholic acid", "liver"),
	("Prednisolone", "liver"),
	("Azathioprine", "liver"),
	("Mycophenolate mofetil", "liver"),
	("Tacrolimus", "liver"),
	("Cyclosporine", "liver"),
	("Everolimus", "liver"),
	("Sirolimus", "liver"),
	("Bictegravir", "liver"),
	("Levothyroxine sodium", "thyroid"),
	("Liothyronine sodium", "thyroid"),
	("Thyroxine sodium", "thyroid"),
	("Desiccated thyroid extract", "thyroid"),
	("Methimazole", "thyroid"),
	("Carbimazole", "thyroid"),
	("Propylthiouracil", "thyroid"),
	("Potassium iodide", "thyroid"),
	("Lugol's iodine", "thyroid"),
	("Sodium iodide", "thyroid"),
	("Iodine-131", "thyroid"),
	("Propranolol", "thyroid"),
	("Atenolol", "thyroid"),
	("Metoprolol", "thyroid"),
	("Diltiazem", "thyroid"),
	("Amiodarone", "thyroid"),
	("Lithium carbonate", "thyroid"),
	("Hydrocortisone", "thyroid"),
	("Prednisolone", "thyroid"),
	("Dexamethasone", "thyroid"),
	("Methylprednisolone", "thyroid"),
	("Cholestyramine", "thyroid"),
	("Selenium", "thyroid"),
	("Vitamin D3 (Cholecalciferol)", "thyroid"),
	("Calcium carbonate", "thyroid"),
	("Calcium citrate", "thyroid"),
	("Calcitriol", "thyroid"),
	("Ergocalciferol", "thyroid"),
	("Alfacalcidol", "thyroid"),
	("Cinacalcet", "thyroid"),
	("Paricalcitol", "thyroid"),
	("Teriparatide", "thyroid"),
	("Bisphosphonates", "thyroid"),
	("Alendronate", "thyroid"),
	("Risedronate", "thyroid"),
	("Zoledronic acid", "thyroid"),
	("Pamidronate", "thyroid"),
	("Etidronate", "thyroid"),
	("Raloxifene", "thyroid"),
	("Tamoxifen", "thyroid"),
	("Clodronate", "thyroid"),
	("Denosumab", "thyroid"),
	("Ibandronate", "thyroid"),
	("Fludrocortisone", "thyroid"),
	("Somatostatin", "thyroid"),
	("Octreotide", "thyroid"),
	("Lanreotide", "thyroid"),
	("Pasireotide", "thyroid"),
	("Prasterone", "thyroid"),
	("Dehydroepiandrosterone", "thyroid"),
	("Atorvastatin", "cholesterol"),
	("Rosuvastatin", "cholesterol"),
	("Simvastatin", "cholesterol"),
	("Pravastatin", "cholesterol"),
	("Lovastatin", "cholesterol"),
	("Fluvastatin", "cholesterol"),
	("Pitavastatin", "cholesterol"),
	("Ezetimibe", "cholesterol"),
	("Fenofibrate", "cholesterol"),
	("Gemfibrozil", "cholesterol"),
	("Bezafibrate", "cholesterol"),
	("Ciprofibrate", "cholesterol"),
	("Niacin", "cholesterol"),
	("Nicotinic acid", "cholesterol"),
	("Omega-3-acid ethyl esters", "cholesterol"),
	("Icosapent ethyl", "cholesterol"),
	("Colestyramine", "cholesterol"),
	("Colestipol", "cholesterol"),
	("Colesevelam", "cholesterol"),
	("Probucol", "cholesterol"),
	("Lomitapide", "cholesterol"),
	("Mipomersen", "cholesterol"),
	("Alirocumab", "cholesterol"),
	("Evolocumab", "cholesterol"),
	("Bempedoic acid", "cholesterol"),
	("Acipimox", "cholesterol"),
	("Pantethine", "cholesterol"),
	("Dalcetrapib", "cholesterol"),
	("Anacetrapib", "cholesterol"),
	("Evacetrapib", "cholesterol"),
	("Torcetrapib", "cholesterol"),
	("Fasudil", "cholesterol"),
	("Elafibranor", "cholesterol"),
	("Saroglitazar", "cholesterol"),
	("Pyridoxine", "cholesterol"),
	("Sitagliptin", "cholesterol"),
	("Liraglutide", "cholesterol"),
	("Semaglutide", "cholesterol"),
	("Metformin", "cholesterol"),
	("Canagliflozin", "cholesterol"),
	("Dapagliflozin", "cholesterol"),
	("Ertugliflozin", "cholesterol"),
	("Empagliflozin", "cholesterol"),
	("Allicin", "cholesterol"),
	("Policosanol", "cholesterol"),
	("Beta-sitosterol", "cholesterol"),
	("Artichoke extract", "cholesterol"),
	("Psyllium husk", "cholesterol"),
	("Curcumin", "cholesterol"),
	("Metformin", "diabetes"),
	("Glimepiride", "diabetes"),
	("Gliclazide", "diabetes"),
	("Glyburide", "diabetes"),
	("Glipizide", "diabetes"),
	("Tolbutamide", "diabetes"),
	("Chlorpropamide", "diabetes"),
	("Acarbose", "diabetes"),
	("Voglibose", "diabetes"),
	("Miglitol", "diabetes"),
	("Pioglitazone", "diabetes"),
	("Rosiglitazone", "diabetes"),
	("Repaglinide", "diabetes"),
	("Nateglinide", "diabetes"),
	("Sitagliptin", "diabetes"),
	("Saxagliptin", "diabetes"),
	("Vildagliptin", "diabetes"),
	("Linagliptin", "diabetes"),
	("Alogliptin", "diabetes"),
	("Dapagliflozin", "diabetes"),
	("Canagliflozin", "diabetes"),
	("Empagliflozin", "diabetes"),
	("Ertugliflozin", "diabetes"),
	("Ipragliflozin", "diabetes"),
	("Luseogliflozin", "diabetes"),
	("Insulin regular", "diabetes"),
	("Insulin NPH", "diabetes"),
    ("Insulin glargine", "diabetes"),
    ("Insulin detemir", "diabetes"),
    ("Insulin degludec", "diabetes"),
    ("Insulin lispro", "diabetes"),
    ("Insulin aspart", "diabetes"),
    ("Insulin glulisine", "diabetes"),
    ("Pramlintide", "diabetes"),
    ("Exenatide", "diabetes"),
    ("Liraglutide", "diabetes"),
    ("Dulaglutide", "diabetes"),
    ("Semaglutide", "diabetes"),
    ("Albiglutide", "diabetes"),
    ("Tirzepatide", "diabetes"),
    ("Bromocriptine", "diabetes"),
    ("Colesevelam", "diabetes"),
    ("Vitamin D", "diabetes"),
    ("Chromium picolinate", "diabetes"),
    ("Berberine", "diabetes"),
    ("Alpha-lipoic acid", "diabetes"),
    ("Fenugreek", "diabetes"),
    ("Gymnema sylvestre", "diabetes"),
    ("Bitter melon extract", "diabetes"),
    ("Cinnamon extract", "diabetes")
]
cursor.executemany("INSERT INTO medicine_disease (medicine_name, disease) VALUES (?, ?)", medicines)
conn.commit()

def fuzzy_match_list_for_disease(disease, ocr_list, threshold=60):
	"""
	Given a disease and OCR list, returns fuzzy matches from the database.
	"""
	# Get medicines for the specific disease
	cursor.execute("SELECT medicine_name FROM medicine_disease WHERE disease = ?", (disease,))
	disease_meds = [row[0] for row in cursor.fetchall()]
	# Get medicines for the 'common' category
	cursor.execute("SELECT medicine_name FROM medicine_disease WHERE disease = ?", ("common",))
	common_meds = [row[0] for row in cursor.fetchall()]

	results = {}
	for med in ocr_list:
		match = process.extractOne(med, disease_meds, scorer=fuzz.token_sort_ratio)
		if match and match[1] >= threshold:
			results[med] = {"match": match[0], "score": match[1], "category": disease}
		else:
			# Try matching in 'common' if not found in disease
			match_common = process.extractOne(med, common_meds, scorer=fuzz.token_sort_ratio)
			if match_common and match_common[1] >= threshold:
				results[med] = {"match": match_common[0], "score": match_common[1], "category": "common"}
			else:
				results[med] = {"match": None, "score": match_common[1] if match_common else 0, "category": None}

	return results
# Example: Fetch all records
# cursor.execute("SELECT * FROM medicine_disease")
# print(cursor.fetchall())


# --- USER TABLE (Unified: user info, long-term disease, past prescriptions) ---
cursor.execute('''
	CREATE TABLE IF NOT EXISTS user (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		user_name TEXT NOT NULL,
		gender TEXT,
		blood_group TEXT,
		mobile_number TEXT,
		long_term_disease TEXT,
		past_prescriptions TEXT
	)
''')
conn.commit()

# Example function to add a user
def add_user(user_name, gender, blood_group, mobile_number, long_term_disease, past_prescriptions):
	conn2 = sqlite3.connect('doseiq.db')
	cursor2 = conn2.cursor()
	cursor2.execute(
		"INSERT INTO user (user_name, gender, blood_group, mobile_number, long_term_disease, past_prescriptions) VALUES (?, ?, ?, ?, ?, ?)",
		(user_name, gender, blood_group, mobile_number, long_term_disease, past_prescriptions)
	)
	conn2.commit()
	conn2.close()

# Function to update past prescriptions summary
def update_past_prescriptions(user_name, summary):
	conn2 = sqlite3.connect('doseiq.db')
	cursor2 = conn2.cursor()
	cursor2.execute(
		"UPDATE user SET past_prescriptions = ? WHERE user_name = ?",
		(summary, user_name)
	)
	conn2.commit()
	conn2.close()

#THIS IS GENERIC MEDICINES DATABASE OF MORE THAN 500 MEDICINES WITH CATEGORIES
# cOMMON,HEART,bLOODpRESSURE,BREATHING,mentALhEALTH,eYE,ent,lIVER,tHYROID,CHOLESTROL,DIABATES
conn.close()

